version: "3.8"

services:
  api:
    build: .
    ports:
      - "9000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-receiptiq}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - HONEYBADGER_API_KEY=${HONEYBADGER_API_KEY}
      - MAILTRAP_API_KEY=${MAILTRAP_API_KEY}
    depends_on:
      - postgres
    networks:
      - receiptiq-network

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-receiptiq}
    ports:
      - "9001:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - receiptiq-network

volumes:
  postgres_data:

networks:
  receiptiq-network:
    driver: bridge
