services:

  postgres:
      image: postgres:15
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        - POSTGRES_DB=${POSTGRES_DB:-receiptiq}
      ports:
        - "9000:${POSTGRES_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - receiptiq-network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
        interval: 10s
        timeout: 5s
  
  redis:
    image: redis:latest
    ports:
      - "9001:6379"
    volumes:
      - redis_data:/data
    networks:
      - receiptiq-network
    command: redis-server --appendonly yes

  api:
    build: .
    ports:
      - "9002:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - receiptiq-network
  
  celery_worker:
    image: receiptiq_api-api
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      
    networks:
      - receiptiq-network
    command: celery -A celery_app worker --loglevel=info
  
  celery_flower:
    image: receiptiq_api-api
    working_dir: /app
    ports:
      - "9003:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres  # Add this if Flower needs database access
      - celery_worker
    networks:
      - receiptiq-network
    command: celery -A celery_app flower --loglevel=info

volumes:
  postgres_data:
  redis_data:

networks:
  receiptiq-network:
    driver: bridge
