services:
  api:
    build: .
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - receiptiq-network

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-receiptiq}
    ports:
      - "9001:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - receiptiq-network

volumes:
  postgres_data:

networks:
  receiptiq-network:
    driver: bridge
