version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=receiptiq
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_AUTH_SOURCE=admin
      - MONGODB_AUTH_MECHANISM=SCRAM-SHA-256
      - SECRET_KEY=${SECRET_KEY}
      - HONEYBADGER_API_KEY=${HONEYBADGER_API_KEY}
      - MAILTRAP_API_KEY=${MAILTRAP_API_KEY}
    depends_on:
      - mongodb
    networks:
      - receiptiq-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - receiptiq-network

volumes:
  mongodb_data:

networks:
  receiptiq-network:
    driver: bridge
