# fly.toml app configuration file generated for receiptiq-api-patient-star-917 on 2025-07-07T13:22:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'receiptiq-api-patient-star-917'
primary_region = 'jnb'

[processes]
app = "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
worker = "celery -A celery_app worker --loglevel=info"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
